# Generated by Django 5.1.4 on 2025-01-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_row_number_alter_employee_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='row_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
